couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 59, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 88, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 58, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 87, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 58, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 87, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 58, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 87, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 58, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 87, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 58, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 86, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 58, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 87, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 58, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 87, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 59, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 86, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
Сгенерированный номер партии: 1 31.07.2024
Номер партии "1 31.07.2024" уже существует.
Internal Server Error: /create_batch/
Traceback (most recent call last):
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py", line 95, in create_batch
    form.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\.venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 59, in save
    self.batch_number = self.generate_batch_number()
  File "C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py", line 86, in generate_batch_number
    raise ValidationError(f'Номер партии "{new_batch_number}" уже существует.')
django.core.exceptions.ValidationError: ['Номер партии "1 31.07.2024" уже существует.']
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
Сгенерированный номер партии: 1 31.07.2024
Сгенерированный номер партии: 2 31.07.2024
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\forms.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\forms.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\forms.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\views.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\forms.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
Queryset for 'batch' field: SELECT "sklad1_batch"."id", "sklad1_batch"."product_id", "sklad1_batch"."line_id", "sklad1_batch"."batch_number", "sklad1_batch"."production_date", "sklad1_batch"."quantity", "sklad1_batch"."is_used" FROM "sklad1_batch" WHERE "sklad1_batch"."quantity" > 0 ORDER BY "sklad1_batch"."batch_number" ASC
Queryset for 'batch' field: SELECT "sklad1_batch"."id", "sklad1_batch"."product_id", "sklad1_batch"."line_id", "sklad1_batch"."batch_number", "sklad1_batch"."production_date", "sklad1_batch"."quantity", "sklad1_batch"."is_used" FROM "sklad1_batch" WHERE "sklad1_batch"."quantity" > 0 ORDER BY "sklad1_batch"."batch_number" ASC
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\forms.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\forms.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\forms.py changed, reloading.
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
Watching for file changes with StatReloader
C:\Users\Administrator\diplom_django\pythonProjectd2\AisbergWater1\sklad1\models.py changed, reloading.
